### ISSUE TITLE
freesasa fails to compile in python 3.7

### ISSUE THREAD

**Issue by schaarj** [freesasa/freesasa-python#4]
`pip install freesasa` fails under python 3. 7 at the following step:

```
 gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/joerg/miniconda3/include -arch x86_64 -I/Users/joerg/miniconda3/include -arch x86_64 -Ilib/src -I. -I/Users/joerg/miniconda3/include/python3.7m -c freesasa.c -o build/temp.macosx-10.7-x86_64-3.7/freesasa.o -DHAVE_CONFIG_H -std=gnu99
    freesasa.c:3586:33: warning: assigning to 'freesasa_classifier *' (aka 'struct freesasa_classifier *') from 'const freesasa_classifier *' (aka 'const struct freesasa_classifier *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        __pyx_v_self->_c_classifier = (&freesasa_default_classifier);
                                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    freesasa.c:13106:65: error: too many arguments to function call, expected 3, have 4
        return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~
    /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stddef.h:105:16: note: expanded from macro 'NULL'
freesasa==2.0.3
    #  define NULL ((void*)0)
                   ^~~~~~~~~~
    freesasa.c:14963:20: warning: returning 'const char *' from a function with result type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                return PyUnicode_AsUTF8(o);
                       ^~~~~~~~~~~~~~~~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
```

**Comment by mittinatten** [comment]
Thanks for reporting! Will investigate.

**Comment by mittinatten** [comment]
What environment are you on? I added 3.7 to my Travis setup and managed to build on Ubuntu and Mac OS X. Had to change Ubuntu distro from Trusty to Xenial, but because of an error when installing Python 3.7 itself, so probably not related.

Here are the builds: https://travis-ci.org/freesasa/freesasa-python/builds/457870703

**Comment by schaarj** [comment]
I tried it in a Conda environment (Python 3.7.0 [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin) on MacOS 10.14.1 and also in the latest official docker container of python (Python 3.7.1 [GCC 6.3.0 20170516] on linux )

**Comment by schaarj** [comment]
Just to add to this: cloning the repo and running `setup.py` works, only installation via pip fails

**Comment by mittinatten** [comment]
Ok, I guess there could be a problem with it not having been released to PyPi for 3.7. Let me make a new post-release and see if that helps.

**Comment by mittinatten** [comment]
The release has been deployed as 2.0.3.post4 (https://pypi.org/project/freesasa/2.0.3.post4/). Can you try again?

**Comment by schaarj** [comment]
thanks, it's however not available via pip (yet) 
```
Could not find a version that satisfies the requirement freesasa==2.0.3.post4 (from versions: 2.0.2b1, 2.0.2b2, 2.0.3, 2.0.3.post1, 2.0.3.post2, 2.0.3.post3)
No matching distribution found for freesasa==2.0.3.post4
```

I'll try again later and keep you posted

**Comment by mittinatten** [comment]
Messed up the Windows build and then made another mistake, so the final version is 2.0.3.post6. But the linux and mac builds are identical between .post6 and .post4.

**Comment by schaarj** [comment]
ok, It's now working on the Mac, the docker image still tries to download the post3 version, but this hopefully resolves itself at some point.

Thank you very much for the quick response.

**Comment by gmacari** [comment]
hello there,
pip install freesasa still fails under python 3. 7 on linux. pip point to freesasa 2.0.3.post3 instead of post6:
pip install freesasa==freesasa2.0.3.post6
Collecting freesasa==freesasa2.0.3.post6
  ERROR: Could not find a version that satisfies the requirement freesasa==freesasa2.0.3.post6 (from versions: 2.0.2b1, 2.0.2b2, 2.0.3, 2.0.3.post1, 2.0.3.post2, 2.0.3.post3)

**Comment by mittinatten** [comment]
Hmm, can you try `pip install freesasa=2.0.3.post6`?

**Comment by mittinatten** [comment]
I see now that the source package is missing from 2.0.3.post6, and that's what should be used for linux. Something must have failed in CD.

**Comment by mittinatten** [comment]
Ok, now the source code is published for -post6 as well.

**Comment by CunliangGeng** [comment]
@mittinatten The `pip install freesasa` and `pip install freesasa==2.0.3.post6` still fail on linux with python(3.7.4, anaconda). The error is:
```
  gcc -pthread -B /home/clgeng/software/anaconda3/envs/test/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ilib/src -I. -I/home/clgeng/software/anaconda3/envs/test/include/python3.7m -c lib/src/util.c -o build/temp.linux-x86_64-3.7/lib/src/util.o -DHAVE_CONFIG_H -std=gnu99
  gcc -pthread -B /home/clgeng/software/anaconda3/envs/test/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ilib/src -I. -I/home/clgeng/software/anaconda3/envs/test/include/python3.7m -c freesasa.c -o build/temp.linux-x86_64-3.7/freesasa.o -DHAVE_CONFIG_H -std=gnu99
  freesasa.c: In function ‘__Pyx_PyCFunction_FastCall’:
  freesasa.c:13555:5: error: too many arguments to function ‘(struct PyObject * (*)(struct PyObject *, struct PyObject * const*, Py_ssize_t))meth’
       return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
       ^
  freesasa.c: In function ‘__Pyx_PyObject_AsStringAndSize’:
  freesasa.c:15576:13: warning: return discards ‘const’ qualifier from pointer target type [enabled by default]
               return PyUnicode_AsUTF8(o);
               ^
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for freesasa
  Running setup.py clean for freesasa
Failed to build freesasa
```

**Comment by mittinatten** [comment]
This seems to be the same issue as https://github.com/mittinatten/freesasa/issues/45. The short term solution there was to build directly from the git repo. It seems something is going on with newer Python versions and/or newer gcc, I will post an update here when we've figured it out (let me know if you find a solution).

**Comment by CunliangGeng** [comment]
Thanks, indeed they look like the same issue.

**Comment by mittinatten** [comment]
Ok, I found the solution, at least it solved the problem on my Mac. Older versions of Cython build invalid Python 3.7-code. With Cython 0.21 I got the same error, after upgrading to Cython 0.29.13 the build worked. I will update the pip-package.

**Comment by CunliangGeng** [comment]
@mittinatten Now it (2.0.3.post7) works on linux, thank you!
